
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lucas
 */
public class park_book extends javax.swing.JFrame {

    /**
     * Creates new form park_book
     */
    public park_book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rb9 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        rb11 = new javax.swing.JRadioButton();
        rb13 = new javax.swing.JRadioButton();
        rb12 = new javax.swing.JRadioButton();
        rb15 = new javax.swing.JRadioButton();
        rb14 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Amusement Park Booking");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 382, 47));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Water park packages", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel1.setOpaque(false);

        buttonGroup2.add(rb9);
        rb9.setText("Number Ten");
        rb9.setToolTipText("Gateway to 10 EXCLUSIVE rides");

        buttonGroup2.add(rb7);
        rb7.setText("DEEP SEA");
        rb7.setToolTipText("All under water Rides");

        buttonGroup2.add(rb6);
        rb6.setText("Rain Party");
        rb6.setToolTipText("Enjoy the Rain Dance");

        buttonGroup2.add(rb8);
        rb8.setText("Pirate Package");
        rb8.setToolTipText("All Thriller Rides");

        buttonGroup2.add(rb10);
        rb10.setText("Godzilla Package");
        rb10.setToolTipText("Access to all Rides");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb7, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(rb8, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(rb9, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(rb10, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rb6)
                .addGap(19, 19, 19)
                .addComponent(rb7)
                .addGap(19, 19, 19)
                .addComponent(rb8)
                .addGap(19, 19, 19)
                .addComponent(rb9)
                .addGap(19, 19, 19)
                .addComponent(rb10)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 142, -1, 251));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Snow park packages", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel3.setOpaque(false);

        buttonGroup3.add(rb11);
        rb11.setText("Yeti's House");
        rb11.setToolTipText("Get Ready for a cold DEATH ");

        buttonGroup3.add(rb13);
        rb13.setText("FIRE  in Snow");
        rb13.setToolTipText("All Thriller Rides");

        buttonGroup3.add(rb12);
        rb12.setText("Bear's Tiffin");
        rb12.setToolTipText("Freaky Winter Activities");

        buttonGroup3.add(rb15);
        rb15.setText("Godzilla Package");
        rb15.setToolTipText("Access to all Rides");

        buttonGroup3.add(rb14);
        rb14.setText("Number Ten");
        rb14.setToolTipText("Gateway to 10 EXCLUSIVE rides");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb12, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(rb13, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(rb14, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(rb15, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rb11)
                .addGap(19, 19, 19)
                .addComponent(rb12)
                .addGap(19, 19, 19)
                .addComponent(rb13)
                .addGap(19, 19, 19)
                .addComponent(rb14)
                .addGap(19, 19, 19)
                .addComponent(rb15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 142, -1, 251));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Theme park packages", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel2.setOpaque(false);

        buttonGroup1.add(rb1);
        rb1.setText("Adventure Package");
        rb1.setToolTipText("outdoor adrenaline boost activities");

        buttonGroup1.add(rb2);
        rb2.setText("Indoor Activities");

        buttonGroup1.add(rb3);
        rb3.setText("Gaming Arena");
        rb3.setToolTipText("EXCLUSIVE Game Zone");

        buttonGroup1.add(rb4);
        rb4.setText("Number Ten");
        rb4.setToolTipText("Gateway to 10 EXCLUSIVE rides");

        buttonGroup1.add(rb5);
        rb5.setText("Godzilla Package");
        rb5.setToolTipText("Access to all Rides");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(rb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(rb1)
                .addGap(19, 19, 19)
                .addComponent(rb2)
                .addGap(19, 19, 19)
                .addComponent(rb3)
                .addGap(19, 19, 19)
                .addComponent(rb4)
                .addGap(19, 19, 19)
                .addComponent(rb5)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 142, 224, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No of persons");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 411, 224, 26));
        getContentPane().add(txtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 413, 122, 26));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 457, 122, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Choose Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 457, 224, 26));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Proceed to Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 522, -1, -1));

        username.setText("Logged in as ");
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 0, 80, 30));

        uname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(uname, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 0, 60, 30));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 570));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setOpaque(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ampark3.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String k=null, l=null, m=null ;int c1=0,c2=0,c3=0;
         int n =Integer.parseInt(txtn.getText());
        Date dates = date.getDate();
        String strdate = DateFormat.getDateInstance().format(dates);
        if(rb1.isSelected()){k="Adventure Package";c1=2000;}
        if(rb2.isSelected()){k="Indoor Activities";c1=1500;}
        if(rb3.isSelected()){k="Gaming Arena";c1=750;}
        if(rb4.isSelected()){k="Number Ten";c1=500;}
        if(rb5.isSelected()){k="Godzilla Package";c1=4500;}
        if(rb6.isSelected()){l="Rain Party";c2=500;}
        if(rb7.isSelected()){l="Deep Sea";c2=1000;}
        if(rb8.isSelected()){l="Pirate Package";c2=1500;}
        if(rb9.isSelected()){l="Number Ten";c2=500;}
        if(rb10.isSelected()){l="Godzilla Package";c2=3000;}
        if(rb11.isSelected()){m="Yeti's House";c3=1000;}
        if(rb12.isSelected()){m="Bear's Tiffin";c3=1500;}
        if(rb13.isSelected()){m="Fire in Snow";c3=2000;}
        if(rb14.isSelected()){m="Number Ten";c3=500;}
        if(rb15.isSelected()){m="Godzilla Package";c3=5000;}
        if(k==null && l==null && m==null){JOptionPane.showMessageDialog(null,"Please select appropriate Package");}
        else{  
         int res = JOptionPane.showConfirmDialog(null,"Confirm your Booking");
        if(res== JOptionPane.YES_OPTION){
        try
        {Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/AmusementPark","root","123456");
            Statement stmt= con.createStatement();
            String que = "insert into parkbook values('"+uname.getText()+"','"+k+"','"+l+"','"+m+"',"+n+",'"+strdate+"',"+(c1+c2+c3)*n+");";
            stmt.executeUpdate(que);
            Booking b=new Booking();
            Booking.uname.setText(uname.getText());
            Booking.amt.setText(""+(c1+c2+c3));
            b.setVisible(true);
            this.dispose();
        }
        catch(Exception e){JOptionPane.showMessageDialog(null,e);}}}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(park_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(park_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(park_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(park_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new park_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb13;
    private javax.swing.JRadioButton rb14;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    private javax.swing.JTextField txtn;
    public static javax.swing.JLabel uname;
    public static javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
