
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenu7 = new javax.swing.JMenu();
        jToggleButton1 = new javax.swing.JToggleButton();
        water = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        aboutus = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gsbhouse = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        snow = new javax.swing.JPanel();
        offers = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        theme = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        tp = new javax.swing.JMenuItem();
        wp = new javax.swing.JMenuItem();
        sp = new javax.swing.JMenuItem();
        gsbh = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        amusedhotel = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();
        username = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        jMenu7.setText("jMenu7");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        water.setBackground(new java.awt.Color(255, 255, 255));
        water.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        water.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homepage.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(720, 578));
        home.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 320, 510));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot_20200111-114731.png"))); // NOI18N
        home.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 419, 310));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mickey-ferris-wheel.gif"))); // NOI18N
        home.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 358, 200));

        aboutus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        aboutus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        aboutus.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 70, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/about us.png"))); // NOI18N
        aboutus.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 520));

        gsbhouse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gsbhouse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Great Stars Big House");
        gsbhouse.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 580, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bean.jpeg"))); // NOI18N
        jLabel10.setText("jLabel10");
        gsbhouse.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 190, 117));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apjkalam.jpeg"))); // NOI18N
        jLabel11.setText("jLabel10");
        gsbhouse.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 177, 130));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modi.jpeg"))); // NOI18N
        jLabel12.setText("jLabel10");
        gsbhouse.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 190, 130));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sachint.jpeg"))); // NOI18N
        jLabel15.setText("jLabel15");
        gsbhouse.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 170, 140));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/teresa.jpeg"))); // NOI18N
        jLabel14.setText("jLabel14");
        gsbhouse.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 130, 130));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obama.jpeg"))); // NOI18N
        jLabel16.setText("jLabel15");
        gsbhouse.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 170, 160));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rajni.jpeg"))); // NOI18N
        jLabel17.setText("jLabel15");
        gsbhouse.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 170, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trmph.jpeg"))); // NOI18N
        jLabel18.setText("jLabel15");
        gsbhouse.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 160, 110));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mj.jpeg"))); // NOI18N
        jLabel19.setText("jLabel15");
        gsbhouse.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, 150));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abrahmln.jpeg"))); // NOI18N
        jLabel20.setText("jLabel15");
        gsbhouse.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 130, 160));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gandhi.jpeg"))); // NOI18N
        jLabel21.setText("jLabel15");
        gsbhouse.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 140, 170));

        jLabel22.setText("jLabel15");
        gsbhouse.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 190, 130));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/einstein.jpeg"))); // NOI18N
        jLabel23.setText("jLabel15");
        gsbhouse.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 170, 110));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jack sparrow.jpeg"))); // NOI18N
        jLabel24.setText("jLabel15");
        gsbhouse.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 120, 150));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images122new.jpeg"))); // NOI18N
        gsbhouse.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 520));

        snow.setBackground(new java.awt.Color(255, 255, 255));
        snow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        snow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        offers.setBackground(new java.awt.Color(255, 255, 255));
        offers.setMinimumSize(new java.awt.Dimension(940, 521));
        offers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel27MousePressed(evt);
            }
        });
        offers.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 110, 60));

        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel28MousePressed(evt);
            }
        });
        offers.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 110, 60));

        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/off1.png"))); // NOI18N
        p1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 520));

        offers.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/off2.png"))); // NOI18N
        p2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 520));

        offers.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/off3.png"))); // NOI18N
        p3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 520));

        offers.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/off4.png"))); // NOI18N
        p4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 520));

        offers.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/off5.png"))); // NOI18N
        p5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 391, 520));

        offers.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theme park offer.jpg"))); // NOI18N
        offers.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 480, 280));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mickey-thanos.gif"))); // NOI18N
        offers.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 312, 200));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("MIKANOS Offer");
        jLabel34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        offers.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 190, 60));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Save 5% on every Disney Rides");
        offers.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 200, 60));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Special prices for MCU Fans");
        offers.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 200, 50));

        theme.setBackground(new java.awt.Color(255, 255, 255));
        theme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        theme.setMinimumSize(new java.awt.Dimension(942, 520));
        theme.setPreferredSize(new java.awt.Dimension(942, 520));
        theme.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theme park.jpg"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        theme.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 890, 260));

        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lost-in-black-hole.gif"))); // NOI18N
        theme.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 310, 290));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/planet coaster.jpg"))); // NOI18N
        jLabel37.setText("jLabel37");
        theme.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 460, 215));

        jLabel38.setBackground(new java.awt.Color(0, 0, 0));
        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("<HTML> <HEAD> <BODY> Into<BR> The <BR> Black <BR> Hole ");
        jLabel38.setOpaque(true);
        theme.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 120, 220));

        jLabel39.setBackground(new java.awt.Color(0, 0, 0));
        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 0, 0));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("*SPECIALS");
        jLabel39.setOpaque(true);
        theme.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 120, 50));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Fastest Coasters and 50+ Adventures Rides");
        theme.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 460, 50));

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setAutoscrolls(true);

        jMenu4.setBorder(null);
        jMenu4.setText("Home    ");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu1.setBorder(null);
        jMenu1.setText("Explore Parks    ");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        tp.setText("Theme Park");
        tp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpMouseClicked(evt);
            }
        });
        tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpActionPerformed(evt);
            }
        });
        jMenu1.add(tp);

        wp.setText("Water Park");
        wp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wpActionPerformed(evt);
            }
        });
        jMenu1.add(wp);

        sp.setText("Snow Park");
        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });
        jMenu1.add(sp);

        gsbh.setText("Great Stars Big House");
        gsbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gsbhActionPerformed(evt);
            }
        });
        jMenu1.add(gsbh);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(null);
        jMenu2.setText("Stay Options    ");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        amusedhotel.setText("AmusedHotel");
        amusedhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amusedhotelActionPerformed(evt);
            }
        });
        jMenu2.add(amusedhotel);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(null);
        jMenu3.setText("Tickets And Promotions    ");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem7.setText("Price and offer");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu8.setBorder(null);
        jMenu8.setText("Park Booking    ");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu5.setBorder(null);
        jMenu5.setText("About us    ");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        about.setText("About Amusement Park ");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        jMenu5.add(about);

        jMenuBar1.add(jMenu5);

        username.setBorder(null);
        username.setText("userid    ");
        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usernameMouseClicked(evt);
            }
        });
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jMenuBar1.add(username);

        jMenu6.setBorder(null);
        jMenu6.setText("Log Out    ");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 961, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(water, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aboutus, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gsbhouse, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(snow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(offers, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(theme, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(water, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(aboutus, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(gsbhouse, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(snow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(offers, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(theme, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      theme.setVisible(false);
       snow.setVisible(false);
       water.setVisible(false);
       offers.setVisible(false);
       gsbhouse.setVisible(false);
       aboutus.setVisible(false);
       home.setVisible(true);
       p2.setVisible(false);
       p3.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
        My_Profile mp = new My_Profile();
        My_Profile.uname.setText(""+username.getText());
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usernameMouseClicked
        // TODO add your handling code here:
        My_Profile mp=new My_Profile();
        My_Profile.uname.setText(""+username.getText());
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usernameMouseClicked

    private void gsbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gsbhActionPerformed
       theme.setVisible(false);
       snow.setVisible(false);
       water.setVisible(false);
       aboutus.setVisible(false);
       offers.setVisible(false);
       gsbhouse.setVisible(true);
       home.setVisible(false);
    }//GEN-LAST:event_gsbhActionPerformed

    private void wpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wpActionPerformed
        // TODO add your handling code here:
       theme.setVisible(false);
       snow.setVisible(false);
       gsbhouse.setVisible(false);
       offers.setVisible(false);
       aboutus.setVisible(false);
       water.setVisible(true);
       home.setVisible(false);
    }//GEN-LAST:event_wpActionPerformed

    private void tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpActionPerformed
       snow.setVisible(false);
       water.setVisible(false);
       gsbhouse.setVisible(false);
       offers.setVisible(false);
       aboutus.setVisible(false);
        theme.setVisible(true);
        home.setVisible(false);
    }//GEN-LAST:event_tpActionPerformed

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        // TODO add your handling code here:
        theme.setVisible(false);
       water.setVisible(false);
       offers.setVisible(false);
       gsbhouse.setVisible(false);
       aboutus.setVisible(false);
        snow.setVisible(true);
        home.setVisible(false);
    }//GEN-LAST:event_spActionPerformed

    private void tpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tpMouseClicked

    private void amusedhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amusedhotelActionPerformed
        // TODO add your handling code here:
        amused_hotels ah = new amused_hotels();
        amused_hotels.tuname.setText(""+username.getText());
        
        ah.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_amusedhotelActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
         theme.setVisible(false);
       snow.setVisible(false);
       water.setVisible(false);
       gsbhouse.setVisible(false);
       aboutus.setVisible(false);
       home.setVisible(false);
       offers.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
        theme.setVisible(false);
       snow.setVisible(false);
       water.setVisible(false);
       offers.setVisible(false);
       gsbhouse.setVisible(false);
       aboutus.setVisible(false);
       home.setVisible(true);
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
       theme.setVisible(false);
       offers.setVisible(false);
       snow.setVisible(false);
       water.setVisible(false);
       gsbhouse.setVisible(false);
       aboutus.setVisible(false);
       home.setVisible(true);
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        int input=JOptionPane.showConfirmDialog(null,"Do you want to log out?");
        if(input==0)
        {
            System.gc();
        java.awt.Window win[]=java.awt.Window.getWindows();
        for(int i=0;i<win.length;i++)
        {
            win[i].dispose();
            win[i]=null;
        }
        login_page lp=new login_page();
        lp.setVisible(true);
        }        
    }//GEN-LAST:event_jMenu6MouseClicked

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        theme.setVisible(false);
        snow.setVisible(false);
        offers.setVisible(false);
        water.setVisible(false);
        gsbhouse.setVisible(false);
        aboutus.setVisible(true);
        home.setVisible(false);
    }//GEN-LAST:event_aboutActionPerformed

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
           if(p1.isVisible()){
       p1.setVisible(false);
       p3.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(false);
       p2.setVisible(true);}
       else    if(p2.isVisible()){
       p1.setVisible(false);
       p2.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(false);
       p3.setVisible(true);}
       else    if(p3.isVisible()){
       p1.setVisible(false);
       p2.setVisible(false);
       p3.setVisible(false);
       p5.setVisible(false);
       p4.setVisible(true);}
       else    if(p4.isVisible()){
       p1.setVisible(false);
       p2.setVisible(false);
       p3.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(true);}
       else    if(p5.isVisible()){
       p2.setVisible(false);
       p3.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(false);
       p1.setVisible(true);
           }
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
       if(p5.isVisible()){
       p1.setVisible(false);
       p2.setVisible(false);
       p3.setVisible(false);
       p5.setVisible(false);
       p4.setVisible(true);}
       else    if(p2.isVisible()){
       p2.setVisible(false);
       p3.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(false);
       p1.setVisible(true);
           }
       else    if(p3.isVisible()){
       p1.setVisible(false);
       p3.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(false);
       p2.setVisible(true);    }
       else    if(p4.isVisible()){
       p1.setVisible(false);
       p2.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(false);
       p3.setVisible(true);}
       else    if(p1.isVisible()){
       p1.setVisible(false);
       p2.setVisible(false);
       p3.setVisible(false);
       p4.setVisible(false);
       p5.setVisible(true);}
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MousePressed

    private void jLabel28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MousePressed
        // TODO add your handling code here:     
    }//GEN-LAST:event_jLabel28MousePressed

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
       park_book pb =new park_book();
       park_book.uname.setText(""+username.getText());
       pb.setVisible(true);this.dispose();
       
    }//GEN-LAST:event_jMenu8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JPanel aboutus;
    public static javax.swing.JMenuItem amusedhotel;
    private javax.swing.JMenuItem gsbh;
    private javax.swing.JPanel gsbhouse;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel offers;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel snow;
    private javax.swing.JMenuItem sp;
    private javax.swing.JPanel theme;
    private javax.swing.JMenuItem tp;
    public static javax.swing.JMenu username;
    private javax.swing.JPanel water;
    private javax.swing.JMenuItem wp;
    // End of variables declaration//GEN-END:variables
}
